### ISSUE TITLE
No space

### ISSUE THREAD

**Issue by Kreisfahrer** [Dmitry-Zhelihovsky/ZDA#1]
![image](https://cloud.githubusercontent.com/assets/5236540/19491325/3975d74e-957b-11e6-80cc-792c65a47b91.png)

**Comment by Dmitry-Zhelihovsky** [comment]
Check https://github.com/Dmitry-Zhelihovsky/ZDA/commit/35da3c3e155c2dafedc516ca659c7a6fc57f9aa0
